language: node_js

node_js:
  - "7"

addons:
  apt:
    packages:
      - xvfb
      - gtk2-engines-pixbuf
      - xfonts-cyrillic
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-base
      - xfonts-scalable

install:
  - npm install

before_script:
  - export DISPLAY=':99.0'
  - sh -e ./xvfb start
  - sleep 3

script:
  - ./cucumber
